import { NovelContent } from '../types';

/**
 * Converts the NovelContent object into a standalone HTML string with inline styles.
 * Designed for compatibility with blog posts (Naver Blog, Tistory, etc.) or external viewers.
 */
export const generateExportHTML = (content: NovelContent): string => {
  const { title, body, meta } = content;

  // Process body text: wrap paragraphs in <p> tags and handle bold text
  const formattedBody = body
    .split('\n')
    .map(line => line.trim())
    .filter(line => line.length > 0 && line !== '---')
    .map(line => {
      // Basic Bold parsing: **text** -> <strong>text</strong>
      const parsedLine = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
      return `<p style="margin-bottom: 1.5em; text-align: justify; line-height: 1.8;">${parsedLine}</p>`;
    })
    .join('');

  return `
<!-- 문장의 연금술사 Generated Content -->
<div style="
  max-width: 800px; 
  margin: 0 auto; 
  font-family: 'Noto Serif KR', serif; 
  color: #111111; 
  background-color: #ffffff; 
  padding: 40px 20px; 
  line-height: 1.8;
">
  <!-- Header -->
  <div style="text-align: center; margin-bottom: 60px;">
    <div style="
      display: inline-block; 
      padding: 6px 16px; 
      background-color: #f3f4f6; 
      color: #6b7280; 
      font-size: 14px; 
      border-radius: 9999px; 
      margin-bottom: 20px; 
      font-family: sans-serif;
    ">
      ${meta.genre}
    </div>
    <h1 style="
      font-size: 32px; 
      font-weight: 700; 
      margin: 0 0 20px 0; 
      line-height: 1.3; 
      word-break: keep-all;
    ">
      ${title}
    </h1>
    <div style="width: 40px; height: 4px; background-color: #fbbf24; margin: 0 auto;"></div>
  </div>

  <!-- Body -->
  <div style="font-size: 17px; color: #374151;">
    ${formattedBody}
  </div>

  <!-- Footer / Author's Note -->
  <div style="
    margin-top: 60px; 
    padding: 30px; 
    background-color: #f9fafb; 
    border-radius: 12px; 
    border: 1px solid #e5e7eb;
  ">
    <h3 style="
      font-family: sans-serif; 
      font-size: 14px; 
      font-weight: 700; 
      color: #9ca3af; 
      margin: 0 0 10px 0; 
      text-transform: uppercase; 
      letter-spacing: 0.05em;
    ">
      작가의 의도 (Author's Note)
    </h3>
    <p style="
      font-style: italic; 
      color: #4b5563; 
      margin: 0; 
      line-height: 1.6;
    ">
      "${meta.intent}"
    </p>
  </div>
  
  <div style="text-align: center; margin-top: 40px; font-size: 12px; color: #d1d5db;">
    Generated by 문장의 연금술사
  </div>
</div>
`;
};